apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application.yml: |-
    server:
      port: 8080

    spring:
      application:
        name: api-gateway
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/users/**,/api/auth/**
              filters:
                - StripPrefix=1
            - id: store-service
              uri: http://store-service:8082
              predicates:
                - Path=/api/stores/**
              filters:
                - StripPrefix=1

    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          probes:
            enabled: true
