apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-store-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-store
spec:
  selector:
    app: postgres-store
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-store
  template:
    metadata:
      labels:
        app: postgres-store
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: store_db
        - name: POSTGRES_USER
          value: store
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-store-pvc
