apiVersion: v1
kind: Secret
metadata:
  name: postgres-store-secret
type: Opaque
stringData:
  # Local/dev-friendly: the precreated DB password used by the postgres-store deployment
  password: "password"
