apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
type: Opaque
stringData:
  # Local/dev-friendly: the precreated DB password used by the postgres-user deployment
  password: "password"
