name: E2E smoke tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-smoke:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24-dind
        options: --init --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start docker-compose
        run: |
          cd backend
          docker compose up -d

      - name: Wait for Postgres (user)
        run: |
          chmod +x backend/scripts/ci-wait-for.sh
          backend/scripts/ci-wait-for.sh localhost 5433 60

      - name: Wait for Postgres (store)
        run: |
          backend/scripts/ci-wait-for.sh localhost 5434 60

      - name: Build backend modules
        run: |
          cd backend
          mvn -DskipTests package -B

      - name: Run user-service jar in background
        run: |
          cd backend/user-service
          nohup java -jar target/user-service-0.1.0-SNAPSHOT.jar > /tmp/user-service.log 2>&1 &
          sleep 5

      - name: Wait for user-service port
        run: |
          backend/scripts/ci-wait-for.sh localhost 8081 30

      - name: Run smoke script
        run: |
          chmod +x backend/scripts/e2e-smoke.sh
          backend/scripts/e2e-smoke.sh

      - name: Start store-service jar in background
        run: |
          cd backend/store-service
          nohup java -jar target/store-service-0.1.0-SNAPSHOT.jar > /tmp/store-service.log 2>&1 &
          sleep 5

      - name: Wait for store-service port
        run: |
          backend/scripts/ci-wait-for.sh localhost 8082 30

      - name: Run store-service smoke script
        run: |
          chmod +x backend/scripts/e2e-store-smoke.sh
          backend/scripts/e2e-store-smoke.sh

      - name: Tear down docker-compose
        if: always()
        run: |
          cd backend
          docker compose down -v

