name: Check formatting

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Run Spotless check
        working-directory: backend
        run: mvn -DskipITs=false -DskipTests=false spotless:check
