name: CI - user-service

on:
  pull_request:
    paths:
      - 'backend/user-service/**'

jobs:
  call-reusable:
    uses: ./.github/workflows/ci-java-reusable.yml
    with:
      module_path: 'backend/user-service'
      run_integration_tests: false
      jdk-version: '21'
